version: '2'
services:
  composer:
    build:
      context: ./.develop/build/composer
      dockerfile: Composer_Dockerfile
    volumes:
      - ./:/var/www/html/paginator
    entrypoint: ['bash', '/var/www/html/paginator/.develop/build/composer/composer.sh']
  php-fpm:
    build:
      context: ./.develop/build/php-fpm
      dockerfile: Php-fpm_Dockerfile
    volumes:
      - ./:/var/www/html/paginator
  nginx:
    build:
      context: ./.develop/build/nginx
      dockerfile: Nginx_Dockerfile
    volumes:
      - ./.develop/build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.develop/build/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/paginator
      - ./.develop/build/nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/server.crt
      - ./.develop/build/nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/server.key
      - ./.develop/build/nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "3000:80"
      - "443:443"
    links:
      - php-fpm
  mysql:
    image: mysql:5.7.25
    volumes:
      - ./.develop/build/database:/var/lib/mysql
    ports:
      - "3696:3306"
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=.qweiop123
